---
- name: Create user with password
  hosts:  all
  vars_files:
    - vars/my_pswd.yaml
  tasks:
    - name: Creating the user and set password
      user:
        name: "{{item}}"
        password: "{{ my_paswd | password_hash('sha512') }}"
        shell: /bin/sh
      loop:
        - alice
        - emad
