---
- name: Print machine ID through fact
  hosts:  all
  gather_facts: yes
  tasks:
    - name:
      debug:
        msg:  >
          System {{ inventory_hostname }} has IPv4 {{ ansible_all_ipv4_addresses }} with MAC {{ ansible_default_ipv4.macaddress }} with python {{ ansible_python_version }} and boot image {{ ansible_cmdline.BOOT_IMAGE }} 
#        var: ansible_all_ipv4_addresses
#      
