---
- name: Install web server
  hosts:  all
  tasks:
    - name: Install HTTPD
      yum:
        name: "{{ansible_facts.ansible_local['custom']['general']['pkg']}}"
        state:  latest

    - name: Start HTTPD service
      service:
        name: "{{ansible_facts.ansible_local['custom']['general']['service']}}"
        state:  "{{ansible_facts.ansible_local['custom']['general']['status']}}"
        enabled: "{{ansible_facts.ansible_local['custom']['general']['enabled']}}"
