---
- name: Install remote facts
  hosts:  all
  vars:
    remote_dir: /etc/ansible/facts.d
    facts_file: custom.fact
  tasks:
    - name: Copy facts file to targets
      copy:
        src:  "{{facts_file}}"
        dest: "{{remote_dir}}"
