---
- name: Deploying VFSTPD
  hosts:  all
  tasks:

  - name: Install VFSTDP
    yum:
      name=vsftpd
  - name: Enable VFSTDP
    service:
      name=vsftpd
      enabled=true
  - name: Create README file
    copy:
      content: "Free downloads for everbody"
      dest: /var/ftp/pub/README
      force:  no
      mode: 0444
